[versions]
agp = "7.0.0-beta02"
kotlin = "1.5.10"
coroutines = "1.5.0"

accompanist = "0.7.1"
androidxhilt = "1.0.0"
androidxlifecycle = "2.4.0-alpha01"
androidxtest = "1.3.0"
coil = "1.2.0"
compose = "1.0.0-beta05"
dagger = "2.35.1"
dbtools = "6.0.0"
espresso = "3.3.0"
hilt = "2.35.1"
ktlint = "0.40.0"
navigation = "2.3.5"
paging = "3.0.0-beta02"
retrofit = "2.9.0"
room = "2.3.0"
work = "2.5.0"

[libraries]
accompanist-coil = { module = "com.google.accompanist:accompanist-coil", version.ref = "accompanist" }
accompanist-flowlayout = { module = "com.google.accompanist:accompanist-flowlayout", version.ref = "accompanist" }
accompanist-insets = { module = "com.google.accompanist:accompanist-insets", version.ref = "accompanist" }

android-gradlePlugin = { module = "com.android.tools.build:gradle", version.ref = "agp" }
android-desugar = "com.android.tools:desugar_jdk_libs:1.1.5"

#androidx-activity-compose = "androidx.activity:activity-compose:1.3.0-alpha06"
androidx-activity = "androidx.activity:activity-ktx:1.2.3"
androidx-appcompat = "androidx.appcompat:appcompat:1.3.0"
androidx-constraintlayout = "androidx.constraintlayout:constraintlayout:2.0.4"
androidx-core = "androidx.core:core-ktx:1.5.0-rc02"
androidx-datastorePrefs = "androidx.datastore:datastore-preferences:1.0.0-beta01"
androidx-fragment = "androidx.fragment:fragment-ktx:1.3.4"
androidx-preference = "androidx.preference:preference-ktx:1.1.1"
androidx-recyclerview = "androidx.recyclerview:recyclerview:1.2.0"
androidx-startup = "androidx.startup:startup-runtime:1.0.0"

androidx-hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "androidxhilt" }
#androidx-hilt-compose = "androidx.hilt:hilt-navigation-compose:1.0.0-alpha01"
androidx-hilt-work = { module = "androidx.hilt:hilt-work", version.ref = "androidxhilt" }

androidx-lifecycle-common-java8 = { module = "androidx.lifecycle:lifecycle-common-java8", version.ref = "androidxlifecycle" }
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidxlifecycle" }
#androidx-lifecycle-viewmodel-compose = "androidx.lifecycle:lifecycle-viewmodel-compose:1.0.0-alpha04"
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidxlifecycle" }
androidx-lifecycle-viewmodel-savedstate = { module = "androidx.lifecycle:lifecycle-viewmodel-savedstate", version.ref = "androidxlifecycle" }

#androidx-navigation-compose = "androidx.navigation:navigation-compose:1.0.0-alpha10"

#androidx-paging-common = { module = "androidx.paging:paging-common-ktx", version.ref = "paging" }
#androidx-paging-compose = "androidx.paging:paging-compose:1.0.0-alpha08"
#androidx-paging-runtime = { module = "androidx.paging:paging-runtime-ktx", version.ref = "paging" }

androidx-navigation-fragment = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation" }
androidx-navigation-safeArgsGradlePlugin = { module = "androidx.navigation:navigation-safe-args-gradle-plugin", version.ref = "navigation" }
androidx-navigation-ui = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation" }

androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-room-testing = { module = "androidx.room:room-testing", version.ref = "room" }

androidx-test-core = { module = "androidx.test:core", version.ref = "androidxtest" }
androidx-test-junit = "androidx.test.ext:junit-ktx:1.1.2"
androidx-test-rules = { module = "androidx.test:rules", version.ref = "androidxtest" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidxtest" }

androidx-test-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }
androidx-test-espresso-contrib = { module = "androidx.test.espresso:espresso-contrib", version.ref = "espresso" }

androidx-work-runtime = { module = "androidx.work:work-runtime-ktx", version.ref = "work" }
androidx-work-gcm = { module = "androidx.work:work-gcm", version.ref = "work" }

coil-coil = { module = "io.coil-kt:coil", version.ref = "coil" }
coil-gif = { module = "io.coil-kt:coil-gif", version.ref = "coil" }

#compose-animation-animation = { module = "androidx.compose.animation:animation", version.ref = "compose" }
#compose-foundation-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
#compose-foundation-layout = { module = "androidx.compose.foundation:foundation-layout", version.ref = "compose" }
#compose-material-iconsext = { module = "androidx.compose.material:material-icons-extended", version.ref = "compose" }
#compose-material-material = { module = "androidx.compose.material:material", version.ref = "compose" }
#compose-ui-test = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }
#compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
#compose-ui-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
#compose-ui-util = { module = "androidx.compose.ui:ui-util", version.ref = "compose" }
#compose-ui-viewbinding = { module = "androidx.compose.ui:ui-viewbinding", version.ref = "compose" }

dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger" }
dagger-dagger = { module = "com.google.dagger:dagger", version.ref = "dagger" }

detekt-gradlePlugin = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin:1.17.1"

dbtools-licenseManager = "org.dbtools:license-manager-gradle-plugin:1.0.0-alpha04"

dbtools-room = { module = "org.dbtools:dbtools-room", version.ref = "dbtools" }
dbtools-roomSqlite = { module = "org.dbtools:dbtools-room-sqliteorg", version.ref = "dbtools" }
dbtools-roomJdbcTest = { module = "org.dbtools:dbtools-room-jdbc-test", version.ref = "dbtools" }

#dokka = "org.jetbrains.dokka:dokka-gradle-plugin:1.4.30"

google-analytics = "com.google.firebase:firebase-analytics-ktx:18.0.2"
google-crashlytics = "com.google.firebase:firebase-crashlytics-ktx:17.4.0"
google-crashlyticsGradle = "com.google.firebase:firebase-crashlytics-gradle:2.5.1"

google-kspGradlePlugin = "com.google.devtools.ksp:com.google.devtools.ksp.gradle.plugin:1.4.30-1.0.0-alpha05" # https://maven.google.com/web/index.html#com.google.devtools.ksp:com.google.devtools.ksp.gradle.plugin
google-material = "com.google.android.material:material:1.4.0-beta01" # https://github.com/material-components/material-components-android/releases
google-servicesgradlePlugin = "com.google.gms:google-services:4.3.8"

# Firebase - https://firebase.google.com/support/release-notes/android
google-firebase-bom = "com.google.firebase:firebase-bom:28.0.1"
google-firebase-analytics = { module = "com.google.firebase:firebase-analytics-ktx" }
google-firebase-config = { module = "com.google.firebase:firebase-config-ktx" }
google-firebase-core = { module = "com.google.firebase:firebase-core" }
google-firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics-ktx" }
google-firebase-crashlyticsGradlePlugin = "com.google.firebase:firebase-crashlytics-gradle:2.6.1"
google-firebase-perf = { module = "com.google.firebase:firebase-perf" }
google-firebase-perfGradlePlugin = "com.google.firebase:perf-plugin:1.3.4"

google-hilt-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
google-hilt-gradlePlugin = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hilt" }
google-hilt-library = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
google-hilt-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "hilt" }

google-play-core = "com.google.android.play:core-ktx:1.8.1" # https://developer.android.com/reference/com/google/android/play/core/release-notes

junit-bom = "org.junit:junit-bom:5.7.2"
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine" }

kotlin-binaryCompatibility = "org.jetbrains.kotlinx:binary-compatibility-validator:0.3.0"
kotlin-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlin-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlin-coroutines-playServices = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services", version.ref = "coroutines" }
kotlin-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
kotlin-extensions = { module = "org.jetbrains.kotlin:kotlin-android-extensions", version.ref = "kotlin" }
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-serialization-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin" }
kotlin-serialization-json = "org.jetbrains.kotlinx:kotlinx-serialization-json:1.2.1"
#kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }

leakCanary = "com.squareup.leakcanary:leakcanary-android:2.7"

okhttp-bom = "com.squareup.okhttp3:okhttp-bom:4.9.1"
okhttp-loggingInterceptor = { module = "com.squareup.okhttp3:logging-interceptor" }
okhttp-okhttp = { module = "com.squareup.okhttp3:okhttp" }
okhttp-mockwebserver = { module = "com.squareup.okhttp3:mockwebserver" }

mockito-core = "org.mockito:mockito-core:3.9.0"
mockito-kotlin = "com.nhaarman.mockitokotlin2:mockito-kotlin:2.2.0"
mockK = "io.mockk:mockk:1.11.0"

playPublisher-gradlePlugin = "com.github.triplet.gradle:play-publisher:3.4.0-agp7.0"

retrofit-retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }

#store = "com.dropbox.mobile.store:store4:4.0.0"

timber = "com.jakewharton.timber:timber:4.7.1"

truth = "com.google.truth:truth:1.1.2"

gradleVersions-gradlePlugin = "com.github.ben-manes:gradle-versions-plugin:0.38.0"

workmanagertools = "org.dbtools:workmanager-tools:1.14.1"

xerial-sqlite = "org.xerial:sqlite-jdbc:3.34.0"













