name: Android CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    # GRADLE_OPTS do not impact the JVM used by the daemon to do the actual builds (gradle.properties is where you configure the daemon's JVM).
    # This only impacts the configuration of the JVM that runs the gradle client. MaxMetaspaceSize is unbounded by default, which leads to a
    # condition where the unbounded metaspace allocations starve some other component of the build, and the gradle daemon disappears.
    # https://docs.gradle.org/6.7.1/userguide/build_environment.html#sec:gradle_environment_variables
    # https://stackoverflow.com/a/69348586/2476068
    env:
      GRADLE_OPTS: -Dorg.gradle.jvmargs="-XX:MaxMetaspaceSize=2g"
      APP_MODULE_NAME: 'android-template'
      CHANGELOG_CMD: 'git log --date=format:"%Y-%m-%d" --pretty="format: * %s% b (%an, %cd)" | head -n 10 > commit-changelog.txt'

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Setup
      env:
        ENCODED_STRING: ${{ secrets.UPLOAD_KEYSTORE }}
        APP_DISTRIBUTION_KEYS: ${{ secrets.APP_DISTRIBUTION_KEYS }}
      run: |
        $CHANGELOG_CMD
        echo $ENCODED_STRING | base64 -d -i > app/upload-keystore
        echo $APP_DISTRIBUTION_KEYS > app/app-distribution.json

    - name: License
      run: ./gradlew createLicenseReport

    - name: Build
      run: ./gradlew clean assembleAlpha bundleAlpha
      env:
        SIGNING_KEYSTORE: upload-keystore
        SIGNING_STORE_PASSWORD: ${{ secrets.UPLOAD_SIGNING_STORE_PASSWORD }}
        SIGNING_KEY_ALIAS: ${{ secrets.UPLOAD_SIGNING_KEY_ALIAS }}
        SIGNING_KEY_PASSWORD: ${{ secrets.UPLOAD_SIGNING_KEY_PASSWORD }}

    - name: Test
      run: ./gradlew testAlphaUnitTest

    - name: Lint
      run: ./gradlew lintAlpha

    - name: Detekt
      run: ./gradlew downloadDetektConfig detekt

    - name: App Distribution
      run: ./gradlew appDistributionUploadAlpha

    - name: Deploy to Play Store
      run: ./gradlew publishAlphaBundle --artifact-dir app/build/outputs/bundle/alpha

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: build-outputs
        path: app/build/outputs

    - name: Upload build reports
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: build-reports
        path: |
          **/build/licenses/*.html
          **/build/test-results/**/TEST-*.xml
          app/build/reports/*.html
          */build/reports/detekt/*.html

#    - name: App Distribution
#      run: ./gradlew downloadDetektConfig detekt
#    - name: Deploy to Play Store
#      run: ./gradlew downloadDetektConfig detekt

#  - name: Deploy to Play Store
#      uses: r0adkll/upload-google-play@v1
#      with:
#        serviceAccountJsonPlainText: ${{ secrets.PUBLISHER_PROPERTIES }}
#        packageName: org.jdc.
#        releaseFiles: app/build/outputs/apk/release/*.aab
#        track: internal
#        status: completed

